prepositions_dets = {
    'altar': ('on', 'an'),
    'balcony': ('on', 'a'),
    'balloon festival': ('at', 'a'),
    'ballroom': ('at', 'a'),
    'baseball field': ('at', 'a'),
    'basketball court': ('at', 'a'),
    'bed': ('on', 'a'),
    'boat': ('on', 'a'),
    'border': ('on', 'the'),
    'bridge': ('on', 'a'),
    'bus stop': ('at', 'a'),
    'campsite': ('at', 'a'),
    'club': ('at', 'the'),
    'coast': ('on', 'the'),
    'country road': ('on', 'a'),
    'crime scene': ('at', 'a'),
    'dock': ('on', 'a'),
    'fair': ('at', 'a'),
    'farm': ('on', 'a'),
    'gas station': ('at', 'a'),
    'grill': ('near', 'a'),
    'gym': ('at', 'the'),
    'hairdresser': ('at', 'the'),
    'kitchen table': ('at', 'the'),
    'lake': ('at', 'the'),
    'lawn': ('on', 'the'),
    'market': ('at', 'a'),
    'mini golf course': ('at', 'a'),
    'monument': ('at', 'a'),
    'mountain': ('on', 'a'),
    'ocean': ('at', 'the'),
    'paintball park': ('at', 'a'),
    'park': ('at', 'a'),
    'patio': ('on', 'a'),
    'political rally': ('at', 'a'),
    'polo field': ('on', 'a'),
    'pool': ('at', 'the'),
    'porch': ('on', 'a'),
    'private deck': ('on', 'a'),
    'racetrack': ('at', 'the'),
    'ranch': ('at', 'a'),
    'road': ('on', 'a'),
    'rodeo': ('at', 'a'),
    'rooftop': ('on', 'a'),
    'running track': ('at', 'a'),
    'rural road': ('on', 'a'),
    'school bus': ('on', 'a'),
    'sea': ('at', 'the'),
    'ski resort': ('at', 'a'),
    'soccer field': ('on', 'a'),
    'sofa': ('on', 'a'),
    'stage': ('on', 'a'),
    'subway platform': ('on', 'a'),
    'white house': ('in', 'the'),
    'woods': ('in', 'the'),    
    'yacht': ('on', 'a'),    
}